;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Thu Oct 23 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
DATA SEGMENT
      PORTA EQU 0C0H
      PORTB EQU 0C2H
      PORTC EQU 0C4H
      A_COM_REG EQU 0C6H
      
      PORTD EQU 0D0H
      PORTE EQU 0D2H
      PORTF EQU 0D4H
      B_COM_REG EQU 0D6H
      
      PORTG EQU 0E0H
      C_COM_REG EQU 0E2H

DATA ENDS

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE, DS:DATA
	
	ORG 0000H

START:
	MOV AX, SEG DATA
	MOV DS, AX
	MOV AX, 0
	MOV SS ,AX
	MOV SP, 0FFFEH
	
	XOR AX, AX
	XOR BX, BX
	XOR CX, CX
	XOR DX, DX
	
        MOV DX, A_COM_REG
	MOV AL, 10001011B
	OUT DX, AL
	
	MOV DX, B_COM_REG
	MOV AL, 10000000B
	OUT DX, AL
	
	MOV DX, C_COM_REG
	MOV AL, 038H
	OUT DX, AL
	
	CHECK:
	    MOV DX, PORTB
	    IN AL, DX
	    
	    CMP AL, 11100110B
	    JE PATTERN4

	    JMP OFF
	    
	    PATTERN4:
        CALL CHECKPAUSE
        CALL CHECKOFF

	PATTERN4_LOOP:
        MOV DX, PORTE
        MOV AL, 00000100B
        OUT DX, AL
        MOV DX, PORTD
        XOR AL, AL
        OUT DX, AL
        MOV DX, PORTF
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 00000010B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 00000001B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTD
        MOV AL, 00000010B
        OUT DX, AL
        MOV DX, PORTE
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 00001000B
        OUT DX, AL
        MOV DX, PORTD
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 00010000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 00100000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 00010000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 00001000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTD
        MOV AL, 00100000B
        OUT DX, AL
        MOV DX, PORTF
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 00001000B
        OUT DX, AL
        MOV DX, PORTD
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 00010000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 00100000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 00010000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 00001000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTD
        MOV AL, 00001000B
        OUT DX, AL
        MOV DX, PORTE
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 00000001B
        OUT DX, AL
        MOV DX, PORTD
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 00000010B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 00000100B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 00000010B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 00000001B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTD
        MOV AL, 00000100B
        OUT DX, AL
        MOV DX, PORTF
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 01000000B
        OUT DX, AL
        MOV DX, PORTD
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 10000000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

	 MOV DX, PORTE
        XOR AL, AL
        OUT DX, AL
        MOV DX, PORTD
        MOV AL, 01000000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 10000000B
        OUT DX, AL
	MOV DX, PORTD
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 01000000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTD
        MOV AL, 00010000B
        OUT DX, AL
        MOV DX, PORTE
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 01000000B
        OUT DX, AL
        MOV DX, PORTD
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 10000000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

	MOV DX, PORTF
        XOR AL, AL
        OUT DX, AL
        MOV DX, PORTD
        MOV AL, 10000000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 10000000B
        OUT DX, AL
	MOV DX, PORTD
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTF
        MOV AL, 01000000B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTD
        MOV AL, 00000001B
        OUT DX, AL
        MOV DX, PORTF
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 00000001B
        OUT DX, AL
        MOV DX, PORTD
        XOR AL, AL
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 00000010B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        MOV DX, PORTE
        MOV AL, 00000100B
        OUT DX, AL
        CALL CHECKPAUSE
        CALL CHECKPATTERNOFF
        CALL DELAY

        JMP PATTERN4_LOOP

	    OFF:
	    MOV DX, PORTD
	    MOV AL, 00000000B
	    OUT DX, AL
	    
	    MOV DX, PORTE
	    MOV AL, 00000000B
	    OUT DX, AL
	    
	    MOV DX, PORTF
	    MOV AL, 00000000B
	    OUT DX, AL
	    
	    JMP CHECK
	    
	    CHECKOFF:
	    MOV DX, PORTB
	    IN AL, DX
	    
	    CMP AL, 11111111B
	    JE CHECKOFF_TO_OFF
	    RET
	    
	    CHECKOFF_TO_OFF:
	    POP BX
	    JMP OFF

	    CHECKPATTERNOFF:
	    MOV DX, PORTB
	    IN AL, DX
	    
	    CMP AL, 11111111B
	    JE PATTERNOFF_TO_OFF
	    CMP AL, 11100110B
	    JE CONTINUE_PATTERN4
	    JMP CHECK
	    
	    PATTERNOFF_TO_OFF:
	    POP BX
	    JMP OFF
	    
	    CONTINUE_PATTERN4:
	    RET
	    
	    CHECKCHANGE:
	    MOV DX, PORTB
	    IN AL, DX

	    CMP AL, 11100110B
	    JE PATTERN4
	    CMP AL, 11111111B 
	    JE OFF

	    RET
	    
	    CHECKPAUSE:
	    MOV DX, PORTB
	    IN AL, DX
	    AND AL, 00000010B
	    CMP AL, 00B
	    JNE CONTINUE_RUN
	    
	    PAUSE_LOOP:
	    MOV DX, PORTB
	    IN AL, DX
	    AND AL, 00000010B
	    CMP AL, 00B
	    JE PAUSE_LOOP

	    CONTINUE_RUN:
	    RET

	    DELAY:
	    MOV BX, 0FFFFH
	    L1:
	    DEC BX
	    NOP
	    JNZ L1
	    RET

ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START