;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue Nov 18 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
DATA SEGMENT

   ORG 04000H
   PORTA EQU 0F0H	; PORTA address
   PORTB EQU 0F2H	; PORTB address
   PORTC EQU 0F4H	; PORTC address
   COM_REG EQU 0F6H	;COM_REG address
   PIC1 EQU 0F8H		; A1 = 0
   PIC2 EQU 0FAH		; A1 = 1
   ICW1 EQU 13H		; 0001 0011
   ICW2 EQU 80H		; 1111 0000 starting required int vector address 80H
   ICW4 EQU 03H		; 0000 0011
   OCW1 EQU 0FEH		; 1111 1000 IR0 unmasked
   MOTOR_FLAG DB 0
   ASTERISK_FLAG DB 0
   NAME_FLAG DB 0
   
   LETTER_J1 DB 11111b,00001b,00001b,00001b,10001b,10001b,01110b
   LETTER_J2 DB 11110b,00010b,00010b,00010b,00010b,00010b,11100b
   LETTER_J3 DB 11100b,00100b,00100b,00100b,00100b,00100b,11000b
   LETTER_J4 DB 11000b,01000b,01000b,01000b,01000b,01000b,10000b
   LETTER_J5 DB 10000b,10000b,10000b,10000b,10000b,10000b,00000b
   
   LETTER_E1 DB 11111b,10000b,10000b,11111b,10000b,10000b,11111b
   LETTER_E2 DB 11110b,00000b,00000b,11110b,00000b,00000b,11110b
   LETTER_E3 DB 11100b,00000b,00000b,11100b,00000b,00000b,11100b
   LETTER_E4 DB 11000b,00000b,00000b,11000b,00000b,00000b,11000b
   LETTER_E5 DB 10000b,00000b,00000b,10000b,00000b,00000b,10000b
   
   LETTER_L1 DB 10000b,10000b,10000b,10000b,10000b,10000b,11111b
   LETTER_L2 DB 00000b,00000b,00000b,00000b,00000b,00000b,11110b
   LETTER_L3 DB 00000b,00000b,00000b,00000b,00000b,00000b,11100b
   LETTER_L4 DB 00000b,00000b,00000b,00000b,00000b,00000b,11000b
   LETTER_L5 DB 00000b,00000b,00000b,00000b,00000b,00000b,10000b

   LETTER_ASTERISK DB 01010b, 10101b, 10101b, 01010b, 10001b, 10101b, 10001b

DATA ENDS

STK  SEGMENT STACK
   BOS DW 512d DUP(?) ; stack depth
   TOS LABEL WORD ; top of stack
STK ENDS

PROCED1 SEGMENT
ISR1 PROC FAR
ASSUME CS:PROCED1, DS:DATA
ORG 01000H 
	;PUSHA
	PUSHF 
	PUSH AX 
	PUSH DX
	MOV NAME_FLAG, 1
	MOV ASTERISK_FLAG, 0
	DONE:
	POP DX 
	POP AX
	POPF 
	IRET 
	ISR1 ENDP 
PROCED1 ENDS

PROCED2 SEGMENT
ISR2 PROC FAR
ASSUME CS:PROCED2, DS:DATA
ORG 02000H 
	;PUSHA
	PUSHF 
	PUSH AX 
	PUSH DX
	MOV MOTOR_FLAG, 1
	DONE:
	POP DX 
	POP AX
	POPF 
	IRET 
	ISR2 ENDP 
PROCED2 ENDS

PROCED3 SEGMENT
ISR3 PROC FAR
ASSUME CS:PROCED3, DS:DATA
ORG 03000H 
	;PUSHA
	PUSHF 
	PUSH AX 
	PUSH DX
	
	MOV AX, DATA
    MOV DS, AX
	
	MOV ASTERISK_FLAG, 1
	MOV NAME_FLAG, 0
	MOV MOTOR_FLAG, 0
	DONE:
	POP DX 
	POP AX
	POPF 
	IRET 
	ISR3 ENDP 
PROCED3 ENDS

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STK
	
	ORG 04000H
	
	XOR AX, AX
	XOR BX, BX
	XOR CX, CX
	XOR DX, DX
	
	START:
        MOV AX, DATA
	MOV DS, AX
	MOV AX, STK
	MOV SS, AX
	LEA SP, TOS
	CLI
	
	MOV DX, COM_REG
	MOV AL, 80H
	OUT DX, AL
	
	MOV DX, PIC1
	MOV AL, ICW1
	OUT DX, AL
	
	MOV DX, PIC2
	MOV AL, ICW2
	OUT DX, AL
	
	MOV AL, ICW4
	MOV AL, OCW1
	OUT DX, AL
	STI
	
	XOR AX, AX
	MOV ES, AX
	
	MOV AX, OFFSET ISR1
	MOV [ES:200H], AX
	MOV AX, SEG ISR1
	MOV [ES:202H], AX
	
	MOV AX, OFFSET ISR2
	MOV [ES:204H], AX
	MOV AX, SEG ISR2
	MOV [ES:206H], AX
	
	; NMI set
	MOV AX, OFFSET ISR3
	MOV [ES:08H], AX
	MOV AX, SEG ISR3
	MOV [ES:0AH], AX
	
	
	HERE:
	CHECK1:
		CMP NAME_FLAG, 1
		JE TOGGLENAME
	TRIGISR2:
	    
	    CMP MOTOR_FLAG, 1
	    JE TOGGLEMOTOR
	   
	 CHECKNMI:
	       CMP ASTERISK_FLAG, 1
	       JE TOGGLE_ASTERISK
	  CHECKOFF:
	     CMP MOTOR_FLAG, 0
	    JE OFFMOTOR
	JMP HERE
	; --- Motor ---
	TOGGLEMOTOR:
		MOV DX, PORTC
		MOV AL, 01H
		OUT DX, AL
	JMP CHECKNMI
	
	OFFMOTOR:
		MOV DX, PORTC
		MOV AL, 00H
		OUT DX, AL
	JMP HERE
	; --- asterisk ---
	TOGGLE_ASTERISK:
		MOV BX, 2
	DISP_ASTERISK1_L:
	DEC BX
	MOV SI, OFFSET LETTER_ASTERISK
	DISP_ASTERISK1:     
	
	       MOV DX, PORTA
		MOV AL, [SI]
		OUT DX, AL
		CALL R1
		INC SI
		CALL DELAY_1MS
		
		MOV DX, PORTA
		MOV AL, [SI]
		OUT DX, AL
		CALL R2
		INC SI
		CALL DELAY_1MS
		
		MOV DX, PORTA
		MOV AL, [SI]
		OUT DX, AL
		CALL R3
		INC SI
		CALL DELAY_1MS
		
		MOV DX, PORTA
		MOV AL, [SI]
		OUT DX, AL
		CALL R4
		INC SI
		CALL DELAY_1MS
		
		MOV DX, PORTA
		MOV AL, [SI]
		OUT DX, AL
		CALL R5
		INC SI
		CALL DELAY_1MS
		
		MOV DX, PORTA
		MOV AL, [SI]
		OUT DX, AL
		CALL R6
		INC SI
		CALL DELAY_1MS
		
		MOV DX, PORTA
		MOV AL, [SI]
		OUT DX, AL
		CALL R7
		CALL DELAY_1MS
		
		CALL CLEAR
	CMP BX, 0
JNE DISP_ASTERISK1_L	
		
	JMP CHECKOFF
	
	TOGGLENAME:
	
	MOV BX, 2
	DISPJ1_L:
	DEC BX
	MOV SI, OFFSET LETTER_J1
	
	DISPJ1:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPJ1_L
      
      MOV BX, 2
	 DISPJ2_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_J2
	 
	 DISPJ2:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPJ2_L
      
      MOV BX, 2
      DISPJ3_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_J3
	 
	 DISPJ3:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPJ3_L
	    
	    MOV BX, 2
	 DISPJ4_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_J4
	 
	 DISPJ4:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPJ4_L
	    
	    MOV BX, 2
	    DISPJ5_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_J5
	 
	 DISPJ5:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPJ5_L
	    
	    MOV BX, 2
	DISPE1_L:
	DEC BX
	MOV SI, OFFSET LETTER_E1
	
	DISPE1:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPE1_L
      
      MOV BX, 2
	 DISPE2_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_E2
	 
	 DISPE2:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPE2_L
      
      MOV BX, 2
      DISPE3_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_E3
	 
	 DISPE3:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPE3_L
	    
	    MOV BX, 2
	 DISPE4_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_E4
	 
	 DISPE4:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPE4_L
	    
	    MOV BX, 2
	    DISPE5_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_E5
	 
	 DISPE5:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPE5_L
	    
	    MOV BX, 2
	DISPL1_L:
	DEC BX
	MOV SI, OFFSET LETTER_L1
	
	DISPL1:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPL1_L
      
      MOV BX, 2
	 DISPL2_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_L2
	 
	 DISPL2:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPL2_L
      
      MOV BX, 2
      DISPL3_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_L3
	 
	 DISPL3:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPL3_L
	    
	    MOV BX, 2
	 DISPL4_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_L4
	 
	 DISPL4:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPL4_L
	    
	    MOV BX, 2
	    DISPL5_L:
	 DEC BX
	 MOV SI, OFFSET LETTER_L5
	 
	 DISPL5:
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R1
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R2
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R3
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R4
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R5
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R6
	    INC SI
	    CALL DELAY_1MS
	    
	    MOV DX, PORTA
	    MOV AL, [SI]
	    OUT DX, AL
	    CALL R7
	    INC SI
	    CALL DELAY_1MS
	    
	    CMP BX, 0
	    JNE DISPL5_L

	
	
	INT 81H
	JMP TRIGISR2
	
	R1:
	 MOV DX, PORTB
	       MOV AL, 1111110B		;INIT ALL ROWS
	       OUT DX, AL
	RET
	R2:
	 MOV DX, PORTB
	       MOV AL, 1111101B		;INIT ALL ROWS
	       OUT DX, AL
	RET
	R3:
	 MOV DX, PORTB
	       MOV AL, 1111011B		;INIT ALL ROWS
	       OUT DX, AL
	RET
	R4:
	 MOV DX, PORTB
	       MOV AL, 1110111B		;INIT ALL ROWS
	       OUT DX, AL
	RET
	R5:
	 MOV DX, PORTB
	       MOV AL, 1101111B		;INIT ALL ROWS
	       OUT DX, AL
	RET
	R6:
	 MOV DX, PORTB
	       MOV AL, 1011111B		;INIT ALL ROWS
	       OUT DX, AL
	RET
	R7:
	 MOV DX, PORTB
	       MOV AL, 0111111B		;INIT ALL ROWS
	       OUT DX, AL
	RET
	
	
	DELAY_1MS:
		MOV CX, 250
   TIMER1:
      NOP
      NOP
      NOP
      NOP
      LOOP TIMER1
   RET
   
	DELAY_5MS:
		MOV BX, 0FFFFFH
	L2:
		DEC BX
		NOP
		JNZ L2
		RET	
	
CLEAR:
	 MOV DX, PORTA
	 MOV AL, 0000B
	 OUT DX, AL
	 CALL R1
	 CALL R2
	 CALL R3
	 CALL R4
	 CALL R5
	 CALL R6
	 CALL R7
	RET
	
CODE    ENDS
        END START
	