;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Oct 1 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT
ORG 03000H
   PORTA EQU 0F0H
   PORTB EQU 0F2H 
   PORTC EQU 0F4H
   CREG  EQU 0F6H		; Control Register address of 8255
DATA ENDS

CODE SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

MAIN:
   ; configure 8255 control register
   MOV DX, CREG
   MOV AL, 89H
   OUT DX, AL

   MOV DX, PORTA
   MOV AL, 00H
   OUT DX, AL
   MOV DX, PORTB
   MOV AL, 00H
   OUT DX, AL

START:
   CALL CHECKOFF 
   
   CMP AL, 00000000B
   JE D0
   CMP AL, 00010000B
   JE D1
   CMP AL, 00100000B
   JE D2
   CMP AL, 00110000B
   JE D3
   CMP AL, 01000000B
   JE D4
   CMP AL, 01010000B
   JE D5
   CMP AL, 01100000B
   JE D6
   CMP AL, 01110000B
   JE D7
   CMP AL, 10000000B
   JE D8
   CMP AL, 10010000B
   JE D9

   JMP START

; --- Digit Routines ---
D0:
   MOV DX, PORTB
   MOV AL, 00111111B 
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 0
   OUT DX, AL
   CALL CHECKOFF
   CALL DELAY_1MS

D1:
   MOV DX, PORTB
   MOV AL, 00000110B   
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 1
   OUT DX, AL
   CALL CHECKOFF
   CALL DELAY_1MS

D2:
   MOV DX, PORTB
   MOV AL, 01011011B   
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 2
   OUT DX, AL
   CALL CHECKOFF
   CALL DELAY_1MS

D3:
   MOV DX, PORTB
   MOV AL, 01001111B  
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 3
   OUT DX, AL
   CALL CHECKOFF
   CALL DELAY_1MS

D4:
   MOV DX, PORTB
   MOV AL, 01100110B   
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 4
   OUT DX, AL
   CALL CHECKOFF
   CALL DELAY_1MS

D5:
   MOV DX, PORTB
   MOV AL, 01101101B   
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 5
   OUT DX, AL
   CALL CHECKOFF
   CALL DELAY_1MS

D6:
   MOV DX, PORTB
   MOV AL, 01111101B   
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 6
   OUT DX, AL
   CALL CHECKOFF
   CALL DELAY_1MS

D7:
   MOV DX, PORTB
   MOV AL, 00000111B  
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 7
   OUT DX, AL
   CALL CHECKOFF
   CALL DELAY_1MS

D8:
   MOV DX, PORTB
   MOV AL, 01111111B   
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 8
   OUT DX, AL
   CALL CHECKOFF
   CALL DELAY_1MS

D9:
   MOV DX, PORTB
   MOV AL, 01101111B  
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 9
   OUT DX, AL
   CALL CHECKOFF
   CALL DELAY_1MS

   JMP START

; --- Off Routine ---
OFF:
   MOV DX, PORTB
   MOV AL, 00000000B
   OUT DX, AL
   MOV DX, PORTA
   MOV AL, 0
   OUT DX, AL
   CALL DELAY_1MS
   JMP START

; --- Delay Routine ---
DELAY_1MS:
   MOV BX, 02CAH
L1:
   DEC BX
   NOP
   JNZ L1
   RET
   
; --- Checkoff routine---
CHECKOFF:

   MOV DX, PORTC
   IN AL, DX
   
   CMP AL, 00000001B
   JE OFF
   
   CMP AL, 00010001B
   JE OFF
   
   CMP AL, 00100001B
   JE OFF
   
   CMP AL, 00110001B
   JE OFF
   
   CMP AL, 01000001B
   JE OFF
   
   CMP AL, 01010001B
   JE OFF
   
   CMP AL, 01100001B
   JE OFF
   
   CMP AL, 01110001B
   JE OFF
   
   CMP AL, 10000001B
   JE OFF
   
   CMP AL, 10010001B
   JE OFF
   
   RET

CODE ENDS
END MAIN
