;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Oct 15 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
DATA SEGMENT
    PORTA   EQU 80H
    PORTB   EQU 82H
    PORTC   EQU 84H
    COM_REG EQU 86H

    USER_CODE   DB 8 DUP(0)
    VERIFY_CODE DB 8 DUP(0)
    CODE_SET    DB 0
DATA ENDS

CODE SEGMENT PUBLIC 'CODE'
    ASSUME CS:CODE, DS:DATA
    
    ORG 0000H
    
    XOR AX, AX
    XOR BX, BX
    XOR CX, CX
    XOR DX, DX

    MOV AX, DATA
    MOV DS, AX

START:

    MOV DX, COM_REG
    MOV AL, 10001001B
    OUT DX, AL

REINIT:
    MOV CX, 0
CHECK_LCD_ON:
    MOV DX, PORTC
    IN AL, DX
    TEST AL, 10H
    IN AL, DX
    AND AL, 0FH
    CMP AL, 0CH
    JNE REINIT

    INC CX
    CALL DELAY_1MS
    CMP CX, 3000
    JB CHECK_LCD_ON

    CALL INIT_LCD

MAIN_INTERFACE:
    CALL SHOW_MENU

REINIT2:
    MOV CX, 0
SCAN_OPTION:
    MOV DX, PORTC
    IN AL, DX
    TEST AL, 10H
    IN AL, DX
    AND AL, 0FH

    CMP AL, 00H
    JE SET_CODE
    CMP AL, 01H
    JE ARM_MODE
    CMP AL, 0EH
    JNE REINIT2

    INC CX
    CALL DELAY_1MS
    CMP CX, 5000
    JB SCAN_OPTION

    MOV AL, 08H
    CALL INST_CTRL
    JMP REINIT

; -----------------------
; OPTION 1: SET CODE
; -----------------------
SET_CODE:
    CALL LCD_RESET
    CALL PROMPT_INPUT
    LEA SI, USER_CODE
    XOR BX, BX
    MOV CX, 8
    CALL INPUT_SEQUENCE
    MOV CODE_SET, 1
    CALL DELAY_1S
    CALL DELAY_1S
    CALL DELAY_1S
    CALL DELAY_1S
    CALL LCD_RESET
    JMP MAIN_INTERFACE

INPUT_SEQUENCE:
WAIT_RELEASE:
    MOV DX, PORTC
    IN AL, DX
    TEST AL, 10H
    JNZ WAIT_RELEASE

    CALL READ_KEY
    CMP CX, 4
    JG LIMIT_REACHED

    CMP AL, 0EH
    JE INPUT_DONE
LIMIT_REACHED:
    CMP AL, 0EH
    JE INPUT_SEQUENCE
    CMP AL, 0CH
    JE INPUT_SEQUENCE
    CMP CX, 0
    JE INPUT_SEQUENCE

    MOV [SI], AL
    INC SI
    DEC CX
    MOV AL, '*'
    CALL DATA_CTRL
    JMP INPUT_SEQUENCE

INPUT_DONE:
    MOV AL, ']'
    CALL DATA_CTRL
    RET

; -----------------------
; OPTION 2: ARM / DISARM
; -----------------------
ARM_MODE:
    MOV AL, CODE_SET
    CMP AL, 00H
    JE SHOW_ERROR

WAIT_FOR_DISARM:
    CALL LCD_RESET
    CALL DELAY_1S
    CALL SHOW_WARNING
    CALL DELAY_1S
    MOV DX, PORTC
    IN AL, DX
    TEST AL, 10H
    JZ WAIT_FOR_DISARM
    IN AL, DX
    AND AL, 0FH
    CMP AL, 0DH
    JNE WAIT_FOR_DISARM

    LEA DI, VERIFY_CODE
    MOV CX, 8
CLEAR_VERIFY_BUF:
    MOV BYTE PTR [DI], 0
    INC DI
    LOOP CLEAR_VERIFY_BUF

VERIFY_INPUT:
    CALL LCD_RESET
    CALL PROMPT_INPUT
    LEA SI, VERIFY_CODE
    MOV CX, 8
    CALL INPUT_SEQUENCE
    CALL DELAY_1S
    CALL DELAY_1S
    CALL DELAY_1S
    CALL DELAY_1S
    CALL LCD_RESET
    XOR AX, AX
    XOR BX, BX
    XOR CX, CX

    LEA SI, USER_CODE
    LEA DI, VERIFY_CODE
    MOV CX, 8
CHECK_MATCH:
    MOV AL, [SI]
    CMP AL, [DI]
    JNE INVALID_ENTRY
    INC SI
    INC DI
    LOOP CHECK_MATCH

    CALL SHOW_SUCCESS
WAIT_SUCCESS:
    CALL READ_KEY
    CMP AL, 0EH
    JNE WAIT_SUCCESS
    CALL LCD_RESET
    JMP MAIN_INTERFACE

INVALID_ENTRY:
    MOV CX, 6
    CALL LCD_RESET
REPEAT_FAIL:
    CALL SHOW_INVALID
    CALL DELAY_1S
    CALL LCD_RESET
    LOOP REPEAT_FAIL
    JMP MAIN_INTERFACE

SHOW_ERROR:
    MOV CX, 6
    CALL LCD_RESET
REPEAT_ERROR:
    CALL SHOW_ERRMSG
    CALL DELAY_1S
    CALL LCD_RESET
    LOOP REPEAT_ERROR
    JMP MAIN_INTERFACE

ENDLESS:
    JMP ENDLESS

; -----------------------
; LCD helper routines (lecture versions)
; -----------------------
LCD_RESET:
    MOV AL, 01H
    CALL INST_CTRL
    CALL INIT_LCD
    CALL DELAY_1S
    RET

;====================================================
; LCD INSTRUCTION CONTROL ROUTINE
;====================================================
INST_CTRL:
    PUSH AX                 ; preserve value of AL
    MOV DX, PORTA           ; set port of LCD data bus (PORTA)
    OUT DX, AL              ; write data in AL to PORTA
    MOV DX, PORTB           ; set port of LCD control lines (PORTB)
    MOV AL, 02H             ; E=1, RS=0 (access instruction reg)
    OUT DX, AL              ; write data in AL to PORTB
    CALL DELAY_1MS          ; delay for 1 ms
    MOV DX, PORTB           ; set port of LCD control lines (PORTB)
    MOV AL, 00H             ; E=0, RS=0
    OUT DX, AL              ; write data in AL to PORTB
    POP AX                  ; restore value of AL
    RET

;====================================================
; LCD DATA CONTROL ROUTINE
;====================================================
DATA_CTRL:
    PUSH AX                 ; preserve value of AL
    MOV DX, PORTA           ; set port of LCD data bus (PORTA)
    OUT DX, AL              ; write data in AL to PORTA
    MOV DX, PORTB           ; set port of LCD control lines (PORTB)
    MOV AL, 03H             ; E=1, RS=1 (access data register)
    OUT DX, AL              ; write data in AL to PORTB
    CALL DELAY_1MS          ; delay for 1 ms
    MOV DX, PORTB           ; set port of LCD control lines (PORTB)
    MOV AL, 01H             ; E=0, RS=1
    OUT DX, AL              ; write data in AL to PORTB
    POP AX                  ; restore value of AL
    RET

;====================================================
; LCD INITIALIZATION ROUTINE
;====================================================
INIT_LCD:
    MOV AL, 38H             ; 8-bit interface, dual-line display
    CALL INST_CTRL          ; write instruction to LCD
    MOV AL, 08H             ; display off, cursor off, blink off
    CALL INST_CTRL          ; write instruction to LCD
    MOV AL, 01H             ; clear display
    CALL INST_CTRL          ; write instruction to LCD
    MOV AL, 06H             ; increment cursor, display shift off
    CALL INST_CTRL          ; write instruction to LCD
    MOV AL, 0CH             ; display on, cursor off, blink off
    CALL INST_CTRL          ; write instruction to LCD
    RET

; -----------------------
; DELAY ROUTINES
; -----------------------
DELAY_1MS:
    MOV BX, 230
D1:
    DEC BX
    NOP
    JNZ D1
    RET

DELAY_1S:
    MOV BX, 20000
D2:
    DEC BX
    NOP
    JNZ D2
    RET

; -----------------------
; KEYPAD READING
; -----------------------
READ_KEY:
    MOV DX, PORTC
WAIT_PRESS:
    IN AL, DX
    TEST AL, 10H
    JZ WAIT_PRESS
    IN AL, DX
    AND AL, 0FH
    RET

; -----------------------
; DISPLAY ROUTINES
; -----------------------
SHOW_MENU:
    MOV AL, 'M'
    CALL DATA_CTRL
    MOV AL, 'A'
    CALL DATA_CTRL
    MOV AL, 'I'
    CALL DATA_CTRL
    MOV AL, 'N'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'M'
    CALL DATA_CTRL
    MOV AL, 'E'
    CALL DATA_CTRL
    MOV AL, 'N'
    CALL DATA_CTRL
    MOV AL, 'U'
    CALL DATA_CTRL

    MOV AL, 0C1H
    CALL INST_CTRL
    MOV AL, '['
    CALL DATA_CTRL
    MOV AL, '1'
    CALL DATA_CTRL
    MOV AL, ']'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'S'
    CALL DATA_CTRL
    MOV AL, 'e'
    CALL DATA_CTRL
    MOV AL, 't'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'c'
    CALL DATA_CTRL
    MOV AL, 'o'
    CALL DATA_CTRL
    MOV AL, 'd'
    CALL DATA_CTRL
    MOV AL, 'e'
    CALL DATA_CTRL

    MOV AL, 095H
    CALL INST_CTRL
    MOV AL, '['
    CALL DATA_CTRL
    MOV AL, '2'
    CALL DATA_CTRL
    MOV AL, ']'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'A'
    CALL DATA_CTRL
    MOV AL, 'r'
    CALL DATA_CTRL
    MOV AL, 'm'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 's'
    CALL DATA_CTRL
    MOV AL, 'y'
    CALL DATA_CTRL
    MOV AL, 's'
    CALL DATA_CTRL
    MOV AL, 't'
    CALL DATA_CTRL
    MOV AL, 'e'
    CALL DATA_CTRL
    MOV AL, 'm'
    CALL DATA_CTRL

    MOV AL, 0D5H
    CALL INST_CTRL
    MOV AL, 'C'
    CALL DATA_CTRL
    MOV AL, 'h'
    CALL DATA_CTRL
    MOV AL, 'o'
    CALL DATA_CTRL
    MOV AL, 'i'
    CALL DATA_CTRL
    MOV AL, 'c'
    CALL DATA_CTRL
    MOV AL, 'e'
    CALL DATA_CTRL
    MOV AL, '?'
    CALL DATA_CTRL
    RET
    
;-------------------------------------------------------
; Display: ERROR: System can not be armed, no code set!
;-------------------------------------------------------
SHOW_ERRMSG:
    MOV AL, 'E'
    CALL DATA_CTRL
    MOV AL, 'R'
    CALL DATA_CTRL
    MOV AL, 'R'
    CALL DATA_CTRL
    MOV AL, 'O'
    CALL DATA_CTRL
    MOV AL, 'R'
    CALL DATA_CTRL
    MOV AL, ':'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'S'
    CALL DATA_CTRL
    MOV AL, 'y'
    CALL DATA_CTRL
    MOV AL, 's'
    CALL DATA_CTRL
    MOV AL, 't'
    CALL DATA_CTRL
    MOV AL, 'e'
    CALL DATA_CTRL
    MOV AL, 'm'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'c'
    CALL DATA_CTRL
    MOV AL, 'a'
    CALL DATA_CTRL
    MOV AL, 'n'
    CALL DATA_CTRL
   
   MOV AL, 0C0H
   CALL INST_CTRL
   MOV AL, 'n'
   CALL DATA_CTRL
   MOV AL, 'o'
   CALL DATA_CTRL
   MOV AL, 't'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 'b'
   CALL DATA_CTRL
   MOV AL, 'e'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 'a'
   CALL DATA_CTRL
   MOV AL, 'r'
   CALL DATA_CTRL
   MOV AL, 'm'
   CALL DATA_CTRL
   MOV AL, 'e'
   CALL DATA_CTRL
   MOV AL, 'd'
   CALL DATA_CTRL
   MOV AL, ','
   CALL DATA_CTRL
   
   MOV AL, 094H
   CALL INST_CTRL
   MOV AL, 'n'
   CALL DATA_CTRL
   MOV AL, 'o'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 'c'
   CALL DATA_CTRL
   MOV AL, 'o'
   CALL DATA_CTRL
   MOV AL, 'd'
   CALL DATA_CTRL
   MOV AL, 'e'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 's'
   CALL DATA_CTRL
   MOV AL, 'e'
   CALL DATA_CTRL
   MOV AL, 't'
   CALL DATA_CTRL
   MOV AL, '!'
   CALL DATA_CTRL
   RET

PROMPT_INPUT:
    MOV AL, 'I'
    CALL DATA_CTRL
    MOV AL, 'n'
    CALL DATA_CTRL
    MOV AL, 'p'
    CALL DATA_CTRL
    MOV AL, 'u'
    CALL DATA_CTRL
    MOV AL, 't'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'A'
    CALL DATA_CTRL
    MOV AL, 'c'
    CALL DATA_CTRL
    MOV AL, 'c'
    CALL DATA_CTRL
    MOV AL, 'e'
    CALL DATA_CTRL
    MOV AL, 's'
    CALL DATA_CTRL
    MOV AL, 's'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'C'
    CALL DATA_CTRL
    MOV AL, 'o'
    CALL DATA_CTRL
    MOV AL, 'd'
    CALL DATA_CTRL
    MOV AL, 'e'
    CALL DATA_CTRL

    MOV AL, 095H
   CALL INST_CTRL
   MOV AL, '['
   CALL DATA_CTRL
   RET


SHOW_WARNING:  ;WARNING: System is armed! ... press 0 to disarm
    MOV AL, 'W'
    CALL DATA_CTRL
    MOV AL, 'A'
    CALL DATA_CTRL
    MOV AL, 'R'
    CALL DATA_CTRL
    MOV AL, 'N'
    CALL DATA_CTRL
    MOV AL, 'I'
    CALL DATA_CTRL
    MOV AL, 'N'
    CALL DATA_CTRL
    MOV AL, 'G'
    CALL DATA_CTRL
    MOV AL, ':'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'S'
    CALL DATA_CTRL
    MOV AL, 'y'
    CALL DATA_CTRL
    MOV AL, 's'
    CALL DATA_CTRL
    MOV AL, 't'
    CALL DATA_CTRL
    MOV AL, 'e'
    CALL DATA_CTRL
    MOV AL, 'm'
    CALL DATA_CTRL

   MOV AL, 0C0H
   CALL INST_CTRL
   MOV AL, 'i'
   CALL DATA_CTRL
   MOV AL, 's'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 'a'
   CALL DATA_CTRL
   MOV AL, 'r'
   CALL DATA_CTRL
   MOV AL, 'm'
   CALL DATA_CTRL
   MOV AL, 'e'
   CALL DATA_CTRL
   MOV AL, 'd'
   CALL DATA_CTRL
   MOV AL, '!'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, '.'
   CALL DATA_CTRL
   MOV AL, '.'
   CALL DATA_CTRL
   MOV AL, '.'
   CALL DATA_CTRL

   MOV AL, 094H
   CALL INST_CTRL
   MOV AL, 'p'
   CALL DATA_CTRL
   MOV AL, 'r'
   CALL DATA_CTRL
   MOV AL, 'e'
   CALL DATA_CTRL
   MOV AL, 's'
   CALL DATA_CTRL
   MOV AL, 's'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, '0'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 't'
   CALL DATA_CTRL
   MOV AL, 'o'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 'd'
   CALL DATA_CTRL
   MOV AL, 'i'
   CALL DATA_CTRL
   MOV AL, 's'
   CALL DATA_CTRL
   MOV AL, 'a'
   CALL DATA_CTRL
   MOV AL, 'r'
   CALL DATA_CTRL
   MOV AL, 'm'
   CALL DATA_CTRL
   RET

SHOW_SUCCESS:  ;SUCCESS: System is disarmed! ... press # to return to main menu
    MOV AL, 'S'
    CALL DATA_CTRL
    MOV AL, 'U'
    CALL DATA_CTRL
    MOV AL, 'C'
    CALL DATA_CTRL
    MOV AL, 'C'
    CALL DATA_CTRL
    MOV AL, 'E'
    CALL DATA_CTRL
    MOV AL, 'S'
    CALL DATA_CTRL
    MOV AL, 'S'
    CALL DATA_CTRL
    MOV AL, ':'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'S'
    CALL DATA_CTRL
    MOV AL, 'y'
    CALL DATA_CTRL
    MOV AL, 's'
    CALL DATA_CTRL
    MOV AL, 't'
    CALL DATA_CTRL
    MOV AL, 'e'
    CALL DATA_CTRL
    MOV AL, 'm'
    CALL DATA_CTRL

   MOV AL, 0C0H
   CALL INST_CTRL
   MOV AL, 'i'
   CALL DATA_CTRL
   MOV AL, 's'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 'd'
   CALL DATA_CTRL
   MOV AL, 'i'
   CALL DATA_CTRL
   MOV AL, 's'
   CALL DATA_CTRL
   MOV AL, 'a'
   CALL DATA_CTRL
   MOV AL, 'r'
   CALL DATA_CTRL
   MOV AL, 'm'
   CALL DATA_CTRL
   MOV AL, 'e'
   CALL DATA_CTRL
   MOV AL, 'd'
   CALL DATA_CTRL
   MOV AL, '!'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, '.'
   CALL DATA_CTRL
   MOV AL, '.'
   CALL DATA_CTRL
   MOV AL, '.'
   CALL DATA_CTRL

   MOV AL, 094H
   CALL INST_CTRL
   MOV AL, 'p'
   CALL DATA_CTRL
   MOV AL, 'r'
   CALL DATA_CTRL
   MOV AL, 'e'
   CALL DATA_CTRL
   MOV AL, 's'
   CALL DATA_CTRL
   MOV AL, 's'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, '#'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 't'
   CALL DATA_CTRL
   MOV AL, 'o'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 'r'
   CALL DATA_CTRL
   MOV AL, 'e'
   CALL DATA_CTRL
   MOV AL, 't'
   CALL DATA_CTRL
   MOV AL, 'u'
   CALL DATA_CTRL
   MOV AL, 'r'
   CALL DATA_CTRL
   MOV AL, 'n'
   CALL DATA_CTRL

   MOV AL, 0D5H
   CALL INST_CTRL
   MOV AL, 't'
   CALL DATA_CTRL
   MOV AL, 'o'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 'm'
   CALL DATA_CTRL
   MOV AL, 'a'
   CALL DATA_CTRL
   MOV AL, 'i'
   CALL DATA_CTRL
   MOV AL, 'n'
   CALL DATA_CTRL
   MOV AL, ' '
   CALL DATA_CTRL
   MOV AL, 'm'
   CALL DATA_CTRL
   MOV AL, 'e'
   CALL DATA_CTRL
   MOV AL, 'n'
   CALL DATA_CTRL
   MOV AL, 'u'
   CALL DATA_CTRL
   RET

SHOW_INVALID:  ;WRONG: Invalid code
    MOV AL, 'W'
    CALL DATA_CTRL
    MOV AL, 'R'
    CALL DATA_CTRL
    MOV AL, 'O'
    CALL DATA_CTRL
    MOV AL, 'N'
    CALL DATA_CTRL
    MOV AL, 'G'
    CALL DATA_CTRL
    MOV AL, ':'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'I'
    CALL DATA_CTRL
    MOV AL, 'n'
    CALL DATA_CTRL
    MOV AL, 'v'
    CALL DATA_CTRL
    MOV AL, 'a'
    CALL DATA_CTRL
    MOV AL, 'l'
    CALL DATA_CTRL
    MOV AL, 'i'
    CALL DATA_CTRL
    MOV AL, 'd'
    CALL DATA_CTRL
    MOV AL, ' '
    CALL DATA_CTRL
    MOV AL, 'c'
    CALL DATA_CTRL
    MOV AL, 'o'
    CALL DATA_CTRL
    MOV AL, 'd'
    CALL DATA_CTRL
    MOV AL, 'e'
    CALL DATA_CTRL
    RET

CODE ENDS
END START
