   ;====================================================================
   ; Main.asm file generated by New Project wizard
   ;
   ; Created:   Sat Nov 22 2025
   ; Processor: 8086
   ; Compiler:  MASM32
   ;
   ; Before starting simulation set Internal Memory Size 
   ; in the 8086 model properties to 0x10000
   ;====================================================================
   PROCEED1 SEGMENT
      ISR0 PROC FAR
	 ASSUME CS:PROCEED1, DS:DATA
	 ORG 01000H
	 
	 PUSHF
	 PUSH AX
	 PUSH DX
	 
	 ;For the Keypad Interrupt Routine
	 CHECK_KEYPAD:
	       CMP POWER_FLAG, 1
	       JNE EXIT_ISR
	       
	       CMP MAINMENUFLAG, 1
	       JNE EXIT_ISR
	       
	       MOV DX, PORTC
	       IN AL, DX
	       AND AL, 0FH
	       
	       CMP AL, 00H
	       JE TEMPCONMENU_JMP
	       
	       CMP AL, 01H
	       JE PHCONMENU_JMP
	       
	       CMP AL, 02H
	       JE TEMPTHRMENU_JMP
	       
	       CMP AL, 04H
	       JE PHTHRMENU_JMP
	       
	       CMP AL, 0CH
	       JE VIEWTHR_JMP
	       
	       JMP EXIT_ISR
	 
	 TEMPCONMENU_JMP:
	       MOV TEMPCONMENU_FLAG, 1
	       MOV MAINMENUFLAG, 0
	       JMP EXIT_ISR
	       
	 PHCONMENU_JMP:
	       MOV PHCONMENU_FLAG, 1
	       MOV MAINMENUFLAG, 0
	       JMP EXIT_ISR
	       
	 TEMPTHRMENU_JMP:
	       MOV TEMPTHRMENU_FLAG, 1
	       MOV MAINMENUFLAG, 0
	       JMP EXIT_ISR
	       
	  PHTHRMENU_JMP:
	       MOV PHTHRMENU_FLAG, 1
	       MOV MAINMENUFLAG, 0
	       JMP EXIT_ISR
	       
	  VIEWTHR_JMP:
	       MOV VIEWTHR_FLAG, 1
	       MOV MAINMENUFLAG, 0
	       JMP EXIT_ISR
	       
	  EXIT_ISR:
	    POP DX
	    POP AX
	    POPF
	    IRET
	 ISR0 ENDP
	 PROCEED1 ENDS
	 
	 PROCEED2 SEGMENT
	   ISR1 PROC FAR
	       ASSUME CS:PROCEED2, DS:DATA
	       ORG 02000H
	       
	       PUSHF
	       PUSH AX
	       PUSH DX
	       
	       MOV ALARMFLAG, 1
	       
	       MOV DX, PORTB
	       MOV AL, 20H
	       OR AL, ENABLE_PORTS
	       MOV ENABLE_PORTS, AL
	       OUT DX, AL
	       
	       EXIT_ISR1:
		  POP DX
		  POP AX
		  POPF
		  IRET
	ISR1 ENDP
	PROCEED2 ENDS
   
   DATA SEGMENT
   ORG 03000H
      PORTADC_A EQU 0C0H          		; Define PORTADC_A address for either input or output (any)
      PORTADC_B EQU 0C2H          		; Define PORTADC_B address for output
      PORTADC_C EQU 0C4H          		; Define PORTADC_C address for input
      PORTADC_COMREG EQU 0C6H        ; Define address for ADC command register
      
      PORTA EQU 0C8H          			; Define PORTA address for output 					(LCD control)
      PORTB EQU 0CAH          			; Define PORTB address for output 					(Enable signals)
      PORTC EQU 0CCH          			; Define PORTC address for input 					(Keypad input)
      PORT_COMREG EQU 0CEH       	; Define address for secondary command register
      
      PORTLCD_A EQU 0D0H          		; Define PORTLCD_A address for output
      PORTLCD_B EQU 0D2H          		; Define PORTLCD_B address for output
      PORTLCD_COMREG EQU 0DEH       ; Define address for tertiary command register
      
      ; --------- Initialization and Operation Command Words ---------
      PIC1 EQU 0F8H
      PIC2 EQU 0FAH
      ICW1 EQU 13H
      ICW2 EQU 84H
      ICW4 EQU 03H
      OCW1_ISR0 EQU 0FEH
      ; -------------------------------------------------------------------------------------
      
      POWER_FLAG DB 0
      MAINMENUFLAG DB 0
      TEMPCONMENU_FLAG DB 0
      TEMPTHRMENU_FLAG DB 0
      PHCONMENU_FLAG DB 0
      PHTHRMENU_FLAG DB 0
      VIEWTHR_FLAG DB 0
      ALARMFLAG DB 0
      
      HEATING_FLAG DB 0
      COOLING_FLAG DB 0
      
      ACID_FLAG DB 0
      ALK_FLAG DB 0
      
      PLACE DB 0
      TENSPLACE DB 0
      ONESPLACE DB 0
      COMBINEDNUM DB 0
      
      ENABLE_PORTS DB 0
      
      PH DB 0
      PHMIN DB 7
      PHMAX DB 9
      
      PHHIGH_FLAG DB 0
      PHLOW_FLAG DB 0
      
      TEMPHIGH_FLAG DB 0
      TEMPLOW_FLAG DB 0
      
      
      TEMP DB 0
      TEMPMIN DB 20							; Initialize desired temperature to 20 degees celsius
      TEMPMAX DB 25
      
      ; ----- DISPLAY LCD ------
      
      TEMP_MSG DB "TEM:	", "$"
      PH_MSG DB "PH:	", "$"
      DEG_C DB 11011111B, "C", "$"
      
      MENU1_MSG DB "[1]TempCon [2]pHCon", "$"
      MENU2_MSG DB "[3]TempThr [4]pHThr", "$"
      BLANK_MSG DB "	", "$"
      VIEWTHR_LABEL DB "[*]ViewThr", "$"
      
      MENU3_MSG DB "[5] HEATING LED: ", "$"
      MENU4_MSG DB "[6] COOLING FAN: ", "$"
      MENU5_MSG DB "[9] BACK ", "$"
      
      MENU6_MSG DB "[7] ACID PUMP: ", "$"
      MENU7_MSG DB "[8] ALK. PUMP: ", "$"
      MENU8_MSG DB "[9] BACK ", "$"
      
      
      ; ---- TEMP THRESH MENU ----
      TEMP_THR_MSG DB "TEMPERATURE", "$"
      TEMPTHR_ERRMIN_MSG DB "MIN MUST NOT >= 40", "$"
      TEMPTHR_ERRMAX_MSG DB "MAX MUST BE > MIN", "$"

      ; ----- PH THRESH MENU ----
      PH_THR_MSG DB "pH", "$"
      PHTHR_ERRMIN_MSG DB "INVALID pH", "$"
      PHTHR_ERRMAX_MSG DB "MAX MUST BE > MIN", "$"
      
      OFF_MSG DB "OFF", "$"
      ON_MSG DB "ON", "$"
      
      
      MIN_MSG DB "MIN:", "$"
      MAX_MSG DB "MAX:", "$"


      ; --- SETTING THRESHOLD ----
      
      MIN_VALUE_FLAG DB 0
      MAX_VALUE_FLAG DB 0
      
       ; =======================MENU FOR VIEW THRESH VALUES ==============================
       
       TEMP_MIN_VIEW DB "TEMPERATURE MIN:", "$"
       TEMP_MAX_VIEW DB "TEMPERATURE MAX:", "$"
       
       PH_MIN_VIEW DB "PH MIN:","$"
       PH_MAX_VIEW DB "PH MAX:", "$"
       
       BACK_OPTION DB "[9] BACK", "$"
      
      
      ; --- WARNING MESSAGES ----
      PHH_WARNING DB 		"phH", "$"		; pH is too High
      PHL_WARNING DB 		"phL", "$"		; pH is too Low
      TEMPH_WARNING DB	"tmpH", "$"		; Temp is too High
      TEMPL_WARNING DB	"tmpL", "$"		; Temp is too Low

      CELSIUS_MSG DB ".0", "$"
      
   DATA ENDS

   STK SEGMENT STACK
	    BOS DW 64d DUP(?)
	    TOS LABEL WORD
   STK ENDS

   CODE    SEGMENT PUBLIC 'CODE'
	   ASSUME CS:CODE, DS:DATA, SS:STK
	  ORG 08000H 

   START:
   
	 MOV AX, DATA
	 MOV DS, AX
	 MOV AX, STK
	 MOV SS, AX
	 LEA SP, TOS
	 
	 CLI
   
   
	 MOV DX, PORTADC_COMREG          	; Initialize command register 1
	 MOV AL, 89H              				; Command to setup register
	 OUT DX, AL
	 
	 MOV DX, PORT_COMREG          		; Initialize command register 2
	 MOV AL, 89H              				; Command to setup register
	 OUT DX, AL
	 
	 MOV DX, PORTLCD_COMREG          	; Initialize command register 3
	 MOV AL, 89H              				; Command to setup register
	 OUT DX, AL
	 
	 MOV DX, PIC1
	 MOV AL, ICW1
	 OUT DX, AL
	 MOV DX, PIC2
	 MOV AL, ICW2
	 OUT DX, AL
	 MOV AL, ICW4
	 OUT DX, AL
	 MOV AL, OCW1_ISR0
	 OUT DX, AL
	 STI

	 ;---------------- Interrupt Vectors ----------------
	 MOV AX, OFFSET ISR0
	 MOV [ES:200H], AX
	 MOV AX, SEG ISR0
	 MOV [ES:202H], AX
	 MOV AX, OFFSET ISR1
	 MOV [ES:204H], AX
	 MOV AX, SEG ISR1
	 MOV [ES:206H], AX
	 ;----------------------------------------------------------
	 
	 CALL INIT_LCD           		; Initialize LCD

      ;FOREGROUND ROUTINE
      HERE:
	 ; -----------------------KEYPAD READING ------------------------
	 READ_KEY:
	    MOV DX, PORTC
	 WAIT_PRESS:
	    IN AL, DX
	    TEST AL, 10H
	    JZ WAIT_PRESS
	    IN AL, DX
	    AND AL, 0FH
	 CMP AL, 0DH
	 JE TOGGLEPOWER
	 JMP HERE
	 
	 TOGGLEPOWER:
	    CMP POWER_FLAG, 0
	    JE POWER_ON
	    
	 OFF:
	    MOV POWER_FLAG, 0
	    MOV DX, PORTB
	    MOV AL, 00H
	    OUT DX, AL
	    JMP HERE
	    
	 POWER_ON:
	    MOV POWER_FLAG, 1
	    MOV DX, PORTB
	    MOV AL, 01H
	    OUT DX, AL
	    JMP SHOW_MENU
	    
	 SHOW_MENU:
	    CALL INIT_LCD
	    MOV AL, 80H
	    CALL INST_CTRL
	    LEA SI, TEMP_MSG
	    CALL PRINT_STR
	    MOV AL, 86H			; Position for temperature value
	    CALL INST_CTRL
	    
	    MOV AL, 0C0H
	    CALL INST_CTRL
	    LEA SI, PH_MSG
	    CALL PRINT_STR
	    MOV AL, 0C6H			; Position for pH value
	    CALL INST_CTRL
	    
	    MOV AL, 94H
	    CALL INST_CTRL
	    LEA SI, MENU1_MSG
	    CALL PRINT_STR
	    
	    MOV AL, 0D4H
	    CALL INST_CTRL
	    LEA SI, MENU2_MSG
	    CALL PRINT_STR
	    
	 JMP GETSENSOR
	 
	 GETSENSOR:
	    ; ; ========== GETTING PH ==========
	    MOV DX, PORTADC_B
	    MOV AL, 00H
	    OUT DX, AL
	    CALL DELAY
	    
	    ; --- SET ALE = 1 TO LATCH ADDRESS
	    MOV AL, 10000B
	    OUT DX, AL
	    CALL DELAY
	    
	    ; --- SET START = 1 TO START CONVERSION
	    MOV AL, 11000B
	    OUT DX, AL
	    CALL DELAY
	    CALL DELAY
	    
	    ; --- SET OE = 1, ALE = 0, START = 0 TO ENABLE DATA OUTPUT
	    MOV AL, 20H
	    OUT DX, AL
	    CALL DELAY
	    
	    MOV DX, PORTADC_C
	    IN AL, DX
	    
	    ; CONVERSION: ANALOG = (DIGITAL * 25) / 256
	    ; PH = (140 - (ANALOG * 14) / 3) / 10
	    
	    XOR DX, DX
	    MOV CX, 25
	    MUL CX	; MULTIPLY 2.5 * 10 TO DIGITAL
	    XOR DX, DX
	    MOV CX, 256
	    DIV CX	; DIVIDE BY 256
	    XOR AH, AH
	    MOV CX, 14
	    MUL CX
	    MOV CX, 3
	    DIV CX
	    MOV CX, 140
	    SUB CX, AX
	    MOV AX, CX
	    
	    XOR AH, AH	; ENSURE AH IS CLEAN
	    MOV BH, 10
	    DIV BH		; AL = TENS DIGIT, AH = ONES DIGIT
	    
	    MOV PH, AL
	    
	    ; --- EXTRACT TENS DIGIT --- (FOR DISPLAY PH)
	    PUSH AX
	    MOV AL, 84H
	    CALL INST_CTRL
	    POP AX
	    XOR AH, AH
	    MOV BH, 10
	    DIV BH
	    
	    ; --- OUTPUT TENS DIGIT TO PORTA ---
	    MOV BL, AL	; BL = TENS
	    ADD BL, 30H	; CONVERT TO ASCII
	    MOV AL, BL
	    CALL DATA_CTRL
	    
	    MOV BL, AH
	    ADD BL, 30H
	    MOV AL, BL
	    CALL DATA_CTRL
	    
	    ; ========== GETTING TEMP ==========
	    MOV DX, PORTADC_B
	    MOV AL, 01H
	    OUT DX, AL
	    CALL DELAY
	    
	    ; SET ALE = 1 TO LATCH ADDRESS
	    MOV AL, 1001B
	    OUT DX, AL
	    CALL DELAY
	    
	    ; SET START = 1 TO START CONVERSION
	    MOV AL, 11001B
	    OUT DX, AL
	    CALL DELAY
	    CALL DELAY
	    
	    ; SET OE = 1, ALE = 0, START = 0 TO ENABLE DATA OUTPUT
	    MOV AL, 21H
	    OUT DX, AL
	    CALL DELAY
	    
	    XOR AX, AX
	    XOR BX, BX
	    XOR CX, CX
	    XOR DX, DX
	    
	    MOV DX, PORTADC_C
	    IN AL, DX		; READ ADC0808 OUTPUT. AL = TEMP INPUT
	    MOV TEMP, AL
	    
	    ; --- EXTRACT TENS DIGIT --- (FOR DISPLAY TEMP)
	    PUSH AX
	    MOV AL, 0C4H
	    CALL INST_CTRL
	    POP AX
	    XOR AH, AH
	    MOV BH, 10
	    DIV BH
	    
	    ; --- OUTPUT TENS DIGIT TO PORTA ---
	    MOV BL, AL
	    ADD BL, 30H
	    MOV AL, BL
	    CALL DATA_CTRL
	    
	    MOV BL, AH
	    ADD BL, 30H
	    MOV AL, BL
	    CALL DATA_CTRL
	    
	    CHECKALARM:
	       MOV AL, PH
	       CMP AL, PHMAX
	       JLE CHECK_PH_LOW
	       
	       ; PH > MAXPH - SET HIGH FLAG AND DISPLAY WARNING
	       
	       MOV PHHIGH_FLAG, 1
	       MOV AL, 0DFH
	       CALL INST_CTRL
	       LEA SI, PHH_WARNING
	       CALL PRINT_STR
	       CALL TRIGALARM
	       JMP CHECK_TEMP_HIGH
	       
	    CHECK_PH_LOW:
	       MOV PHHIGH_FLAG, 0
	       
	       ; CHECK IF PH < PHMIN
	       MOV AL, PH
	       CMP AL, PHMIN
	       JGE CHECK_TEMP_HIGH
	       
	       ; PH < PHMIN - SET LOW FLAG AND DISPLAY WARNING
	       
	       MOV PHLOW_FLAG, 1
	       MOV AL, 0E4H
	       CALL INST_CTRL
	       LEA SI, PHL_WARNING
	       CALL PRINT_STR
	       CALL TRIGALARM
	       JMP CHECK_TEMP_HIGH
	       
	    CHECK_PH_LOW_ELSE:
	       MOV PHLOW_FLAG, 0
	       
	    CHECK_TEMP_HIGH:
	       ; CHECK IF TEMP > TEMPMAX
	       MOV AL, TEMP
	       CMP AL, TEMPMAX
	       JLE CHECK_TEMP_LOW
	       
	       ; TEMP > TEMPMAX - SET HIGH FLAG AND DISPLAY WARNING
	       MOV TEMPHIGH_FLAG, 1
	       MOV AL, 0DFH
	       CALL INST_CTRL
	       LEA SI, TEMPH_WARNING
	       CALL PRINT_STR
	       CALL TRIGALARM
	       JMP CHECK_TEMP_LOW_ELSE
	       
	    CHECK_TEMP_LOW:
	       MOV TEMPHIGH_FLAG, 0
	       
	       ; CHECK IF TEMP < TEMPMIN
	       MOV AL, TEMP
	       CMP AL, TEMPMIN
	       JGE CLEAR_ALARM_FLAG
	       
	       ; TEMP < TEMPMIN - SET LOW FLAG AND DISPLAY WARNING
	       MOV TEMPLOW_FLAG, 1
	       MOV AL, 0E4H
	       CALL INST_CTRL
	       LEA SI, TEMPL_WARNING
	       CALL PRINT_STR
	       CALL TRIGALARM
	       JMP CLEAR_ALARM_FLAG
	       
	    CHECK_TEMP_LOW_ELSE:
	       MOV TEMPLOW_FLAG, 0
	       
	    CLEAR_ALARM_FLAG:
	       MOV ALARMFLAG, 0
	       JMP CONTMENU
	       
	    TRIGALARM:
	       INT 81H
	       
	    CONTMENU:
	       CMP ALARMFLAG, 0
	       JNE COMPMENUFLAGS
	       MOV ALARMFLAG, 0
	       
	    COMPMENUFLAGS:
	       CMP TEMPCONMENU_FLAG, 1
	       JE TEMPCONMENU
	       
	       CMP PHCONMENU_FLAG, 1
	       JE PHCONMENU
	       
	       CMP TEMPTHRMENU_FLAG, 1
	       JE TEMPTHRMENU
	       
	       CMP PHTHRMENU_FLAG, 1
	       JE PHTHRMENU
	       
	       CMP VIEWTHR_FLAG, 1
	       JE VIEWTHRMENU
	       
	       JMP HERE
	       
	    ; =============== TEMPERATURE CONTROL MENU =======================
	       
	    TEMPCONMENU:
	       CALL INIT_LCD
	       MOV AL, 80H
	       CALL INST_CTRL
	       LEA SI, MENU3_MSG
	       CALL PRINT_STR
	       MOV AL, 86H			
	       CALL INST_CTRL
	    
	       MOV AL, 0C0H		
	       CALL INST_CTRL
	       LEA SI, MENU4_MSG
	       CALL PRINT_STR
	       MOV AL, 0C6H
	       CALL INST_CTRL
	    
	       MOV AL, 94H
	       CALL INST_CTRL
	       LEA SI, MENU5_MSG
	       CALL PRINT_STR
	       
	       ; -----------------------
	       ; KEYPAD READING
	       ; -----------------------
	       READ_KEY_TEMP:
		  MOV DX, PORTC
	       WAIT_PRESS_TEMP:
		  IN AL, DX
		  TEST AL, 10H
		  JZ WAIT_PRESS_TEMP
		  IN AL, DX
		  AND AL, 0FH
		  
		  CMP AL, 05H
		  JE HEATTOGGLE
		  
		  CMP AL, 06H
		  JE COOLTOGGLE
		  
		  CMP AL, 09H
		  JE SHOW_MENU
		  
		  CMP HEATING_FLAG, 1
		  JE ONHEATING
		  
		  MOV AL, 90H
		  CALL INST_CTRL
		  LEA SI, OFF_MSG
		  CALL PRINT_STR
		  JMP CHECKCOOLING

		  CHECKCOOLING:
		     CMP COOLING_FLAG, 1
		     JE ONCOOLING
		     
		     MOV AL, 0A4H
		     CALL INST_CTRL
		     LEA SI, OFF_MSG
		     CALL PRINT_STR
		     JMP READ_KEY_TEMP
		     
		  ONHEATING:
		     MOV AL, 90H
		     CALL INST_CTRL
		     LEA SI, ON_MSG
		     CALL PRINT_STR
		     JMP CHECKCOOLING

		  ONCOOLING:
		     MOV AL, 0A4H
		     CALL INST_CTRL
		     LEA SI, ON_MSG
		     CALL PRINT_STR
		     JMP READ_KEY_TEMP
		  
		  HEATTOGGLE:
		     CMP HEATING_FLAG, 0
		     JE SET_HEAT_ON
		     MOV HEATING_FLAG, 0
		     JMP HEAT_OFF
		     
		  SET_HEAT_ON:
		     MOV HEATING_FLAG, 1
		     
		     CMP HEATING_FLAG, 1
		     JE HEAT_ON
		     
		  HEAT_ON:
		     MOV DX, PORTB
		     MOV AL, 10H
		     OR AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     
		     MOV COOLING_FLAG, 0
		     MOV DX, PORTB
		     MOV AL, 0F7H
		     AND AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     
		     JMP READ_KEY

		  HEAT_OFF:
		     MOV DX, PORTB
		     MOV AL, 11101111B
		     AND AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     
		     JMP READ_KEY
		     
		  COOLTOGGLE:
		     CMP COOLING_FLAG, 0
		     JE SET_COOL_ON
		     MOV COOLING_FLAG, 0
		     JMP COOL_OFF
		     
		  SET_COOL_ON:
		     MOV COOLING_FLAG, 1
		     CMP COOLING_FLAG, 1
		     JE COOL_ON
		     
		  COOL_OFF:
		     MOV DX, PORTB
		     MOV AL, 0F7H
		     AND AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     JMP READ_KEY
		     
		  COOL_ON:
		     MOV DX, PORTB
		     MOV AL, 08H
		     OR AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     
		     MOV HEATING_FLAG, 0
		     MOV DX, PORTB
		     MOV AL, 0EFH
		     AND AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     
		     JMP READ_KEY
		     
		     
		  ; =========== PH CONTROL MENU ==================
	       PHCONMENU:
	       CALL INIT_LCD
	       MOV AL, 80H
	       CALL INST_CTRL
	       LEA SI, MENU6_MSG
	       CALL PRINT_STR
	       MOV AL, 86H			
	       CALL INST_CTRL
	    
	       MOV AL, 0C0H		
	       CALL INST_CTRL
	       LEA SI, MENU7_MSG
	       CALL PRINT_STR
	       MOV AL, 0C6H
	       CALL INST_CTRL
	    
	       MOV AL, 94H
	       CALL INST_CTRL
	       LEA SI, MENU8_MSG
	       CALL PRINT_STR
	       
	       ; -----------------------
	       ; KEYPAD READING
	       ; -----------------------
	       READ_KEY_PH:
		  MOV DX, PORTC
	       WAIT_PRESS_PH:
		  IN AL, DX
		  TEST AL, 10H
		  JZ WAIT_PRESS_PH
		  IN AL, DX
		  AND AL, 0FH
		  
		  CMP AL, 07H
		  JE ACIDTOGGLE
		  
		  CMP AL, 08H
		  JE ALKTOGGLE
		  
		  CMP AL, 09H
		  JE SHOW_MENU
		  
		   CMP ACID_FLAG, 1
		  JE ONACID
		  
		  MOV AL, 90H
		  CALL INST_CTRL
		  LEA SI, OFF_MSG
		  CALL PRINT_STR
		  JMP CHECKALK

		  CHECKALK:
		     CMP ALK_FLAG, 1
		     JE ONALK
		     
		     MOV AL, 0A4H
		     CALL INST_CTRL
		     LEA SI, OFF_MSG
		     CALL PRINT_STR
		     JMP READ_KEY_PH
		     
		  ONACID:
		     MOV AL, 90H
		     CALL INST_CTRL
		     LEA SI, ON_MSG
		     CALL PRINT_STR
		     JMP CHECKALK

		  ONALK:
		     MOV AL, 0A4H
		     CALL INST_CTRL
		     LEA SI, ON_MSG
		     CALL PRINT_STR
		     JMP READ_KEY_PH
		  
		  JMP PHCONMENU
		  
		  ACIDTOGGLE:
		     CMP ACID_FLAG, 0
		     JE SET_ACID_ON
		     MOV ACID_FLAG, 0
		     JMP ACID_OFF
		     
		  SET_ACID_ON:
		     MOV ACID_FLAG, 1
		     
		     CMP ACID_FLAG, 1
		     JE ACID_ON
		     
		  ACID_ON:
		     MOV DX, PORTB
		     MOV AL, 02H
		     OR AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     
		     MOV ALK_FLAG, 0
		     MOV DX, PORTB
		     MOV AL, 0FBH
		     AND AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     
		     JMP READ_KEY

		  ACID_OFF:
		     MOV DX, PORTB
		     MOV AL, 0FDH
		     AND AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     
		     JMP READ_KEY
		     
		  ALKTOGGLE:
		     CMP ALK_FLAG, 0
		     JE SET_ALK_ON
		     MOV ALK_FLAG, 0
		     JMP ALK_OFF
		     
		  SET_ALK_ON:
		     MOV ALK_FLAG, 1
		     CMP ALK_FLAG, 1
		     JE ALK_ON
		     
		  ALK_OFF:
		     MOV DX, PORTB
		     MOV AL, 0FBH
		     AND AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     JMP READ_KEY
		     
		  ALK_ON:
		     MOV DX, PORTB
		     MOV AL, 04H
		     OR AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     
		     MOV ACID_FLAG, 0
		     MOV DX, PORTB
		     MOV AL, 0FDH
		     AND AL, ENABLE_PORTS
		     MOV ENABLE_PORTS, AL
		     OUT DX, AL
		     
		     JMP READ_KEY
		     
; ================================================================================================== 
	       TEMPTHRMENU:
		  CALL INIT_LCD
		  
		  MOV AL, 80H
		  CALL INST_CTRL
		  LEA SI, TEMP_THR_MSG
		  CALL PRINT_STR
		  
		  MOV AL, 0C0H
		  CALL INST_CTRL
		  LEA SI, MIN_MSG
		  CALL PRINT_STR
		  
		  MOV AL, 94H
		  CALL INST_CTRL
		  LEA SI, MAX_MSG
		  CALL PRINT_STR
		  
	       PHTHRMENU:
		  CALL INIT_LCD
		  
		  MOV AL, 80H
		  CALL INST_CTRL
		  LEA SI, PH_THR_MSG
		  CALL PRINT_STR
		  
		  MOV AL, 0C0H
		  CALL INST_CTRL
		  LEA SI, MIN_MSG
		  CALL PRINT_STR
		  
		  MOV AL, 94H
		  CALL INST_CTRL
		  LEA SI, MAX_MSG
		  CALL PRINT_STR 
		  
	       MOV AL, 0C5H
	       CALL INST_CTRL
	       JMP CHECK_DAVBL
	       
; =========================== SETTING THRESHOLD ======================================================================= 
	       
	       CHECK_DAVBL:
		  MOV DX, PORTC
		  IN AL, DX
		  AND AL, 10H
		  TEST AL, 10H
		  JZ CHECK_DAVBL
		  
		  CMP PLACE, 2
		  JNE PROCESS_KEY
		  
		  RESET_PLACE:
		     MOV PLACE, 0
		     MOV AL, TENSPLACE
		     MOV BL, 10
		     MUL BL
		     ADD AL, ONESPLACE
		     MOV COMBINEDNUM, AL
		     
		     CMP MIN_VALUE_FLAG, 0
		     JE SET_MIN
		     JMP SET_MAX
		     
		  PROCESS_KEY:
		     CMP AL, 0DH 		; check if key pressed is 0
		     JE KEY_D0
		     
		     CMP AL, 00H 		; check if key pressed is 1
		     JE KEY_D1
		     
		     CMP AL, 01H 		; check if key pressed is 2
		     JE KEY_D2
		     
		     CMP AL, 02H 		; check if key pressed is 3
		     JE KEY_D3
		     
		     CMP AL, 04H 		; check if key pressed is 4
		     JE KEY_D4
		     
		     CMP AL, 05H 		; check if key pressed is 5
		     JE KEY_D5
		     
		     CMP AL, 06H 		; check if key pressed is 6
		     JE KEY_D6
		     
		     CMP AL, 08H 		; check if key pressed is 7
		     JE KEY_D7
		     
		     CMP AL, 09H 		; check if key pressed is 8
		     JE KEY_D8
		     
		     CMP AL, 0AH 		; check if key pressed is 9
		     JE KEY_D9
		     
		     
		  KEY_D0:
		     MOV AL, 00H
		     ADD AL, 30H
		     CALL DATA_CTRL
		     SUB AL, 30H
		     JMP CONT
		     
		  KEY_D1:
		     MOV AL, 01H
		     ADD AL, 30H
		     CALL DATA_CTRL
		     SUB AL, 30H
		     JMP CONT
		     
		  KEY_D2:
		     MOV AL, 02H
		     ADD AL, 30H
		     CALL DATA_CTRL
		     SUB AL, 30H
		     JMP CONT
		     
		  KEY_D3:
		     MOV AL, 03H
		     ADD AL, 30H
		     CALL DATA_CTRL
		     SUB AL, 30H
		     JMP CONT
		     
		  KEY_D4:
		     MOV AL, 04H
		     ADD AL, 30H
		     CALL DATA_CTRL
		     SUB AL, 30H
		     JMP CONT
		     
		  KEY_D5:
		     MOV AL, 05H
		     ADD AL, 30H
		     CALL DATA_CTRL
		     SUB AL, 30H
		     JMP CONT
		     
		  KEY_D6:
		     MOV AL, 06H
		     ADD AL, 30H
		     CALL DATA_CTRL
		     SUB AL, 30H
		     JMP CONT
		     
		  KEY_D7:
		     MOV AL, 07H
		     ADD AL, 30H
		     CALL DATA_CTRL
		     SUB AL, 30H
		     JMP CONT
		     
		  KEY_D8:
		     MOV AL, 08H
		     ADD AL, 30H
		     CALL DATA_CTRL
		     SUB AL, 30H
		     JMP CONT
		     
		  KEY_D9:
		     MOV AL, 09H
		     ADD AL, 30H
		     CALL DATA_CTRL
		     SUB AL, 30H
		     JMP CONT

		  CONT:
		     CMP PLACE, 0
		     JNE STORE_ONES
		     MOV TENSPLACE, AL
		     JMP INC_PLACE
		     
		  STORE_ONES:
		     CMP PLACE, 1
		     JNE INC_PLACE
		     MOV ONESPLACE, AL
		     
		     INC_PLACE:
			INC PLACE
			JMP CHECK_DAVBL
		     
		  SET_MIN:
		     MOV MIN_VALUE_FLAG, 1
		     
		     CMP TEMPTHRMENU_FLAG, 1
		     JNE CHECK_PH_MIN
		     
		     MOV AL, COMBINEDNUM
		     CMP AL, 40
		     JL VALID_TEMP_MIN
		     
		     MOV AL, 0D4H
		     CALL INST_CTRL
		     LEA SI, TEMPTHR_ERRMIN_MSG
		     CALL PRINT_STR
		     CALL DELAY
		     CALL DELAY
		     CALL RESET_FLAGS
		     JMP BACK
		     
		  VALID_TEMP_MIN:
		     MOV TEMPMIN, AL
		     JMP CLEAR_AND_CONTINUE
		     
		  CHECK_PH_MIN:
		     CMP PHTHRMENU_FLAG, 1
		     JNE CLEAR_AND_CONTINUE
		     
		     MOV AL, TENSPLACE
		     CMP AL, 0
		     JE CHECK_PH_RANGE
		     CMP AL, 1
		     JE CHECK_PH_RANGE
		     
		     MOV AL, 0D4H
		     CALL INST_CTRL
		     LEA SI, PHTHR_ERRMIN_MSG
		     CALL PRINT_STR
		     CALL DELAY
		     CALL DELAY
		     CALL RESET_FLAGS
		     JMP BACK
		     
		  CHECK_PH_RANGE:
		     MOV AL, COMBINEDNUM
		     CMP AL, 14		; PH CANNOT EXCEED 14
		     JLE VALID_PH_MIN
		     
		     ; IF PH TOO HIGH
		     MOV AL, 0D4H
		     CALL INST_CTRL
		     LEA SI, PHTHR_ERRMAX_MSG
		     CALL PRINT_STR
		     CALL DELAY
		     CALL DELAY
		     CALL RESET_FLAGS
		     JMP BACK
		     
		  VALID_PH_MIN:
		     MOV PHMIN,AL
		     JMP CLEAR_AND_CONTINUE
		     
		  SET_MAX:
		     CMP TEMPTHRMENU_FLAG, 1
		     JNE CHECK_PH_MAX
		     
		     MOV AL, COMBINEDNUM
		     CMP AL, 0
		     JLE INVALID_TEMP_MAX
		     CMP AL, TEMPMIN
		     JG VALID_TEMP_MAX
		     
		  INVALID_TEMP_MAX:
		     MOV AL, 0D4H
		     CALL INST_CTRL
		     LEA SI, TEMPTHR_ERRMAX_MSG
		     CALL PRINT_STR
		     CALL DELAY
		     CALL DELAY
		     CALL RESET_FLAGS
		     JMP BACK
		     
		  VALID_TEMP_MAX:
		     MOV TEMPMAX, AL
		     JMP CLEAR_AND_RETURN
		     
		  CHECK_PH_MAX:
		     CMP PHTHRMENU_FLAG, 1
		     JNE CLEAR_AND_RETURN
		     
		     MOV AL, COMBINEDNUM
		     CMP AL, 0
		     JLE INVALID_PH_MAX
		     CMP AL, PHMIN
		     JG VALID_PH_MAX
		     
		  INVALID_PH_MAX:
		     MOV AL, 0D4H
		     CALL INST_CTRL
		     LEA SI, PHTHR_ERRMAX_MSG
		     CALL PRINT_STR
		     CALL DELAY
		     CALL DELAY
		     CALL RESET_FLAGS
		     JMP BACK
		     
		  VALID_PH_MAX:
		     MOV PHMAX, AL
		     JMP CLEAR_AND_RETURN
		     
		  CLEAR_AND_CONTINUE:
		     MOV TENSPLACE, 0
		     MOV ONESPLACE, 0
		     MOV COMBINEDNUM, 0
		     JMP CHECK_DAVBL
		     
		  CLEAR_AND_RETURN:
		     CALL DELAY
		     CALL DELAY
		     MOV TENSPLACE, 0
		     MOV ONESPLACE, 0
		     MOV COMBINEDNUM, 0
		     JMP BACK
		     
		  RESET_FLAGS:
		     MOV PLACE, 0
		     MOV MIN_VALUE_FLAG, 0
		     MOV TENSPLACE, 0
		     MOV ONESPLACE, 0
		     MOV COMBINEDNUM, 0
		     RET
		     
		  BACK:
		     MOV TEMPCONMENU_FLAG, 0
		     MOV PHCONMENU_FLAG, 0
		     MOV TEMPTHRMENU_FLAG, 0
		     MOV PHTHRMENU_FLAG, 0
		     MOV VIEWTHR_FLAG, 0
		     
		     MOV PLACE, 0
		     MOV MIN_VALUE_FLAG, 0
		     MOV TENSPLACE, 0
		     MOV ONESPLACE, 0
		     MOV COMBINEDNUM, 0
		     
		     MOV MAINMENUFLAG, 1
		     
		     JMP SHOW_MENU
		     
 ; =======================MENU FOR VIEW THRESH VALUES ======================================================================= 
	       VIEWTHRMENU:
		  CALL INIT_LCD
		  
		  ; TEMPERATURE MIN
		  MOV AL, 80H
		  CALL INST_CTRL
		  LEA SI, TEMP_MIN_VIEW
		  CALL PRINT_STR
		  MOV AL, 8FH
		  CALL INST_CTRL
		  MOV AL, TEMPMIN
		  CALL DISPLAY_TWO_DIGITS
		  
		  ; TEMPERATURE MAX
		  MOV AL, 0C0H
		  CALL INST_CTRL
		  LEA SI, TEMP_MAX_VIEW
		  CALL PRINT_STR
		  MOV AL, 0CFH
		  CALL INST_CTRL
		  MOV AL, TEMPMAX
		  CALL DISPLAY_TWO_DIGITS
		  
		  ; PH MIN
		  MOV AL, 94H
		  CALL INST_CTRL
		  LEA SI, PH_MIN_VIEW
		  CALL PRINT_STR
		  MOV AL, 9AH
		  CALL INST_CTRL
		  MOV AL, PHMIN
		  CALL DISPLAY_TWO_DIGITS
		  
		  ; PH MAX
		  MOV AL, 0D4H
		  CALL INST_CTRL
		  LEA SI, PH_MAX_VIEW
		  CALL PRINT_STR
		  MOV AL, 0DAH
		  CALL INST_CTRL
		  MOV AL, PHMAX
		  CALL DISPLAY_TWO_DIGITS
		  
		  ; [9] BACK
		  MOV AL, 0E1H
		  CALL INST_CTRL
		  LEA SI, BACK_OPTION
		  CALL PRINT_STR
		  
	CHECK_VIEWTHRMENU_CHOICE:
	    MOV DX, PORTC
	    IN AL, DX
	    AND AL, 10H
	    JZ CHECK_VIEWTHRMENU_CHOICE
	    
	    MOV DX, PORTC
	    IN AL, DX
	    AND AL, 10H		; NOT SURE IF 10H OR 0FH
	 
	    ; CHECK IF KEY IS 9 (BACK)
	    CMP AL, 0AH
	    JE BACK
	 
	    JMP CHECK_VIEWTHRMENU_CHOICE
	    
	       
	    DISPLAY_TWO_DIGITS:
	       ; --- EXTRACT TENS DIGIT --- (FOR DISPLAY PH)
	    XOR AH, AH
	    MOV BH, 10
	    DIV BH

	    MOV BL, AL
	    ADD BL, 30H	; CONVERT TO ASCII
	    MOV AL, BL
	    CALL DATA_CTRL
	    
	    MOV BL, AH
	    ADD BL, 30H
	    MOV AL, BL
	    CALL DATA_CTRL
	    
	    RET
	    
      ENDLESS:
	 NOP                       						; Endless loop (idle)
	 JMP ENDLESS
	 
      INST_CTRL:
	 PUSH AX                  				; Instruction control subroutine for LCD
	 MOV DX, PORTLCD_A
	 OUT DX, AL
	 MOV DX, PORTLCD_B
	 MOV AL, 02H
	 OUT DX, AL
	 CALL DELAY_1MS
	 MOV DX, PORTLCD_B
	 MOV AL, 00H
	 OUT DX, AL
	 POP AX
	 RET

      DATA_CTRL:
	 PUSH AX                  				; Data control subroutine for LCD
	 MOV DX, PORTLCD_A
	 OUT DX, AL
	 MOV DX, PORTLCD_B
	 MOV AL, 03H
	 OUT DX, AL
	 CALL DELAY_1MS
	 MOV DX, PORTLCD_B
	 MOV AL, 01H
	 OUT DX, AL
	 POP AX
	 RET

      INIT_LCD:
	 MOV AL, 38H             				; Initialize LCD settings (8-bit mode, 2 lines)
	 CALL INST_CTRL
	 MOV AL, 08H             				; Display off
	 CALL INST_CTRL
	 MOV AL, 01H             				; Clear display
	 CALL INST_CTRL
	 MOV AL, 06H             				; Increment cursor
	 CALL INST_CTRL
	 MOV AL, 0CH 			    			; Display on, cursor off
	 CALL INST_CTRL
	 RET

      DELAY:
	 MOV BX, 0FCAH           				; Delay loop
      L1:
	 DEC BX
	 NOP
	 JNZ L1
	 RET
	 
	 DELAY_1MS:
	 MOV BX, 02CAH           				; Delay loop
      L2:
	 DEC BX
	 NOP
	 JNZ L2
	 RET

	 PRINT_STR:
	    MOV AL, [SI]       					; Display each character
	    CMP AL, "$"        					; End of string marker
	    JE EXIT_STR           				; Jump Exit if end of string
	    CALL DATA_CTRL     				; Display character on LCD
	    INC SI            		 			; Next character
	    JMP PRINT_STR
	    EXIT_STR:
	    RET

   CODE ENDS
   END START


	   
